# Generated by Django 4.2.8 on 2026-06-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created'], 'verbose_name': 'کد تایید', 'verbose_name_plural': 'کدهای تایید'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب\u200cهای کاربری'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='affiliation_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_token',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
