# Generated by Django 4.2.8 on 2026-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_collection_created_at_collection_updated_at'),
        ('accounts', '0002_alter_customer_options_alter_otpcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, to='musics.singer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_collections',
            field=models.ManyToManyField(blank=True, to='musics.collection'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_songs',
            field=models.ManyToManyField(blank=True, to='musics.song'),
        ),
    ]
