# Generated by Django 4.2.8 on 2026-06-21 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=150, verbose_name='نام خواننده')),
                ('song_name', models.CharField(max_length=150, verbose_name='نام آهنگ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده'), ('added', 'اضافه شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست آهنگ',
                'verbose_name_plural': 'درخواست\u200cهای آهنگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
