# Generated by Django 4.2.8 on 2026-06-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_favorite_artists_and_more'),
        ('dashboard', '0002_ticket_ticketreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='main_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.ticket'),
        ),
    ]
