# Generated by Django 4.2.8 on 2026-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
