# Generated by Django 4.2.8 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_song_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
