# Generated by Django 4.2.8 on 2026-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_tag_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='synced_lyrics',
            field=models.JSONField(blank=True, help_text='JSON structure containing timestamps, text and translation', null=True),
        ),
    ]
