# Generated by Django 4.2.8 on 2026-06-19 07:11

from django.db import migrations, models
import musics.models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_lyrics_synced_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=musics.models.upload_to),
        ),
    ]
