# Generated by Django 4.2.8 on 2026-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
