# Generated by Django 4.2.8 on 2026-06-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_singer_is_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='title',
        ),
    ]
