# Generated by Django 4.2.8 on 2026-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_rename_name_playlist_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(to='musics.singer')),
                ('collections', models.ManyToManyField(to='musics.collection')),
                ('slider_songs', models.ManyToManyField(to='musics.song')),
                ('special_tags', models.ManyToManyField(to='musics.tag')),
            ],
        ),
    ]
