# Generated by Django 4.2.8 on 2026-06-21 14:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(default='پیام خود را وارد نمایید.')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_logo', models.ImageField(default='media/11.png', upload_to=info.models.upload_to)),
                ('icon', models.ImageField(default='media/11.png', upload_to=info.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=1024, null=True)),
                ('site_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('about_page_description', ckeditor.fields.RichTextField(blank=True, default='insert the post body', null=True)),
                ('footer_description', models.TextField(blank=True, null=True)),
                ('policies', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('aparat', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('bale', models.CharField(blank=True, max_length=255, null=255)),
                ('rubika', models.CharField(blank=True, max_length=255, null=255)),
                ('seo_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.logo')),
            ],
        ),
    ]
