# Generated by Django 4.2.8 on 2026-06-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFAQ',
        ),
    ]
